apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }}
spec:
  type: {{ .Values.svctype }}
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
