{{- if .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruoyi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect-code: "308"
    nginx.ingress.kubernetes.io/ssl-protocols: "TLSv1.2 TLSv1.3"
spec:
  ingressClassName: {{ .Values.className }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.secret }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: {{ .Values.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ui.svcname }}
                port:
                  number: {{ .Values.ui.port }}
{{- end }}
